server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            search-locations: classpath:/config
        git:
            uri: https://github.com/Azure/reddog-solutions
            search-paths: config-server
            default-label: main
        bootstrap: true