apiVersion: v1
kind: ConfigMap
metadata:
  name: reddog-env-vars
  namespace: reddog
data:
  AZURECOSMOSDBURI: 'https://reddog17069briar25730.documents.azure.com:443/'
  AZURECOSMOSDBKEY: 'o3oTZYahKvIIqTrjokKvJqEkWYCX78X6zXttej20YkLVisJDLq1XCnMLqV2LuTB4b4l9v0iYDQUpACDbjihTbQ: : '
  AZURECOSMOSDBDATABASENAME: 'reddog' 
  KAFKASASLJAASCONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username: "$ConnectionString" password: "Endpoint: sb://ehreddog17069briar25730.servicebus.windows.net/;SharedAccessKeyName: RootManageSharedAccessKey;SharedAccessKey: BVN6ZfERj5ZWOozubeuZyAXcfcHCmxIrSoemNOsZTvg: ";'
  KAFKABOOTSTRAPSERVERS: 'ehreddog17069briar25730.servicebus.windows.net:9093'
  KAFKASECURITYPROTOCOL: 'SASL_SSL'
  KAFKASASLMECHANISM: 'PLAIN'
  KAFKATOPICNAME: 'reddog'
  MYSQLURL: 'jdbc:mysql://sqlreddog17069briar25730.mysql.database.azure.com/reddog'
  MYSQLUSER: 'reddog'
  MYSQLPASSWORD: 'w@lkingth3d0g'
  AZUREREDISHOST: 'redisreddog17069briar25730.redis.cache.windows.net'
  AZUREREDISPORT: '6380'
  AZUREREDISACCESSKEY: 'xflO2gahlvjBkHsDsfJLx4WMp1B54UuzeAzCaKdfANs: '
  AZURESTORAGEACCOUNTNAME: 'reddog17069briar25730'
  AZURESTORAGEACCOUNTKEY: 'YjTPG4Rj0bYeuchyMbL8WtCGL2fHY5/hoqLp6Pbc+VG0U8HG2HgApiVCxsd+4mPbk9GTCqjRWhd6+AStWq6TpQ: : '
  AZURESTORAGEENDPOINT: 'https://reddog17069briar25730.blob.core.windows.net'
