apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: reddog
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: "ghcr.io/azure/reddog-retail-demo/reddog-retail-ui:latest"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: reddog  
  labels:
    name: ui
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: ui 