openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8707
    description: Generated server url
paths:
  /orders:
    get:
      tags:
        - accounting-controller
      operationId: getAllInFlightOrders
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderSummaryDto'
  /orders/{period}/{timeStart}/{timeEnd}:
    get:
      tags:
        - accounting-controller
      operationId: getOrderCountWithinTimeInterval
      parameters:
        - name: period
          in: path
          required: true
          schema:
            type: string
        - name: timeStart
          in: path
          required: true
          schema:
            type: string
        - name: timeEnd
          in: path
          required: true
          schema:
            type: string
        - name: store-id
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrdersTimeSeries'
  /orders/{period}/{timeSpan}:
    get:
      tags:
        - accounting-controller
      operationId: getOrdersByPeriod
      parameters:
        - name: period
          in: path
          required: true
          schema:
            type: string
        - name: timeSpan
          in: path
          required: true
          schema:
            type: string
        - name: store-id
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/OrdersTimeSeries'
  /orders/day:
    get:
      tags:
        - accounting-controller
      operationId: getOrdersGroupedByDay
      parameters:
        - name: store-id
          in: header
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChartKeyValueLong'
  /orders/completed:
    get:
      tags:
        - accounting-controller
      operationId: getAllCompletedOrders
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderSummaryDto'
components:
  schemas:
    OrderItemSummaryDto:
      type: object
      properties:
        unitPrice:
          type: number
          format: double
        quantity:
          type: integer
          format: int32
        productId:
          type: integer
          format: int32
        unitCost:
          type: number
          format: double
        imageUrl:
          type: string
        productName:
          type: string
    OrderSummaryDto:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        lastModifiedAt:
          type: string
          format: date-time
        orderCompletedDate:
          type: string
          format: date
        loyaltyId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        orderId:
          type: string
        storeId:
          type: string
        orderDate:
          type: string
          format: date-time
        orderDateInstant:
          type: integer
          format: int64
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemSummaryDto'
        orderTotal:
          type: number
          format: double
        origin:
          type: string
        storeLatitude:
          type: string
        storeLongitude:
          type: string
    OrdersTimeSeries:
      type: object
      properties:
        storeId:
          type: string
        values:
          type: array
          items:
            $ref: '#/components/schemas/TimeSeriesInteger'
    TimeSeriesInteger:
      type: object
      properties:
        pointInTime:
          type: string
          format: date-time
        value:
          type: integer
          format: int32
    ChartKeyValueLong:
      type: object
      properties:
        label:
          type: string
        pv:
          type: integer
          format: int64
