openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8702
    description: Generated server url
paths:
  /product-images:
    post:
      tags:
        - product-controller
      operationId: generateProductImagesFromDiffusion
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  type: string
  /order:
    post:
      tags:
        - order-controller
      operationId: order
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerOrderDto'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderSummaryDto'
  /products:
    get:
      tags:
        - product-controller
      operationId: getAllProducts
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDto'
components:
  schemas:
    CustomerOrderDto:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        lastModifiedAt:
          type: string
          format: date-time
        customerId:
          type: integer
          format: int64
        loyaltyId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        storeId:
          type: string
        origin:
          type: string
        storeLatitude:
          type: string
        storeLongitude:
          type: string
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/CustomerOrderItemDto'
    CustomerOrderItemDto:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        lastModifiedAt:
          type: string
          format: date-time
        productId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
    OrderItemSummaryDto:
      type: object
      properties:
        unitPrice:
          type: number
          format: double
        quantity:
          type: integer
          format: int32
        productId:
          type: integer
          format: int32
        unitCost:
          type: number
          format: double
        imageUrl:
          type: string
        productName:
          type: string
    OrderSummaryDto:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        lastModifiedAt:
          type: string
          format: date-time
        orderCompletedDate:
          type: string
          format: date
        loyaltyId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        orderId:
          type: string
        storeId:
          type: string
        orderDate:
          type: string
          format: date-time
        orderDateInstant:
          type: integer
          format: int64
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemSummaryDto'
        orderTotal:
          type: number
          format: double
        origin:
          type: string
        storeLatitude:
          type: string
        storeLongitude:
          type: string
    ProductDto:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        lastModifiedAt:
          type: string
          format: date-time
        unitPrice:
          type: number
          format: double
        productId:
          type: integer
          format: int32
        unitCost:
          type: number
          format: double
        imageUrl:
          type: string
        description:
          type: string
        productName:
          type: string
        categoryId:
          type: string
