openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8706
    description: Generated server url
paths:
  /orders/{storeId}:
    post:
      tags:
        - virtual-worker-controller
      operationId: checkOrders
      parameters:
        - name: storeId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /orders/complete:
    post:
      tags:
        - virtual-worker-controller
      operationId: completeOrders
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderSummaryDto'
components:
  schemas:
    OrderItemSummaryDto:
      type: object
      properties:
        unitPrice:
          type: number
          format: double
        quantity:
          type: integer
          format: int32
        productId:
          type: integer
          format: int32
        unitCost:
          type: number
          format: double
        imageUrl:
          type: string
        productName:
          type: string
    OrderSummaryDto:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        lastModifiedAt:
          type: string
          format: date-time
        orderCompletedDate:
          type: string
          format: date
        loyaltyId:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        orderId:
          type: string
        storeId:
          type: string
        orderDate:
          type: string
          format: date-time
        orderDateInstant:
          type: integer
          format: int64
        orderItems:
          type: array
          items:
            $ref: '#/components/schemas/OrderItemSummaryDto'
        orderTotal:
          type: number
          format: double
        origin:
          type: string
        storeLatitude:
          type: string
        storeLongitude:
          type: string
