# multi-stage build
FROM openjdk:17-jdk-alpine as builder
RUN apk add --no-cache maven
RUN mkdir /project
COPY . /project
WORKDIR /project
RUN ls -la
RUN pwd
RUN mvn package -DskipTests

# Using MS Build of OpenJDK image
#FROM mcr.microsoft.com/openjdk/jdk:17-ubuntu
FROM openjdk:17-jdk-alpine
# Secure way to run the container as non-root user
RUN apk add dumb-init
RUN mkdir /app
RUN addgroup --system reddoguser && adduser -S -s /bin/false -G reddoguser reddoguser
RUN ls -la
COPY --from=build /project/target/*SNAPSHOT.jar /app/app.jar
WORKDIR /app
RUN chown -R reddoguser:reddoguser /app
USER reddoguser
ARG PORT=8704
EXPOSE ${PORT}
CMD "dumb-init" "java" "-jar" "app.jar"