spring:
  kafka:
    topic:
      name: ${KAFKATOPICNAME:reddogoct3}
      group: ${KAFKATOPICGROUP:order-service}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        sasl:
          mechanism: ${KAFKASASLMECHANISM:PLAIN}
          jaas:
            config: ${KAFKASASLJAASCONFIG}
        spring:
          json:
            type:
              mapping: ordersummary:com.microsoft.gbb.rasa.orderservice.dto.OrderSummaryDto
      bootstrap-servers: ${KAFKABOOTSTRAPSERVERS:localhost:9092}
    security:
      protocol: ${KAFKASECURITYPROTOCOL:PLAINTEXT}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
  config:
    import: optional:classpath:.env[.properties]
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQLPASSWORD}
    username: ${MYSQLUSER}
    url: ${MYSQLURL}
  flyway:
    baseline-on-migrate: 'true'
  banner:
    location: static/banner.txt
eureka:
  client:
    register-with-eureka: 'false'
    fetch-registry: 'false'
springdoc:
  swagger-ui:
    enabled: 'true'
    path: /swagger
  api-docs:
    path: /api-docs
topic:
  name:
    producer: ${KAFKATOPICNAME:reddogoct3}
server:
  port: '8082'
