apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
  namespace: reddog
spec:
  selector:
    matchLabels:
      app: order-service
  template:
    spec:
      containers:
        - name: order-service
          image: crenqzyghyv6nfi.azurecr.io/gkdemostorestore/gkdemostorestore:azdev-deploy-1665697477