apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: reddog
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8702
      targetPort: 8702