spring:
  application:
    name: virtual-worker
  banner:
    location: static/banner.txt
data:
  STORE_ID: ${STORE_ID:Redmond}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
server:
  port: 8086
springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger
        enabled: true
---
spring:
  profiles: dev
  application:
    name: virtual-worker